import { db } from "./db";
import { exercises } from "../shared/schema";
export async function seedCatalogue() {
  const [existing] = await db
    .select({ id: exercises.id })
    .from(exercises)
    .limit(1);
  if (!existing)
    await db.insert(exercises).values([
      // Chest
      {
        name: "Bench Press",
        category: "Strength",
        muscleGroup: "Chest",
        description: "Flat barbell bench press",
      },
      {
        name: "Incline DB Press",
        category: "Strength",
        muscleGroup: "Chest",
        description: "Incline dumbbell press",
      },
      {
        name: "Chest Fly",
        category: "Strength",
        muscleGroup: "Chest",
        description: "Dumbbell chest fly",
      },
      {
        name: "Cable Crossover",
        category: "Strength",
        muscleGroup: "Chest",
        description: "Cable crossover fly",
      },
      {
        name: "Push-Up",
        category: "Bodyweight",
        muscleGroup: "Chest",
        description: "Standard push-up",
      },
      {
        name: "Decline Press",
        category: "Strength",
        muscleGroup: "Chest",
        description: "Decline barbell press",
      },
      {
        name: "Svend Press",
        category: "Strength",
        muscleGroup: "Chest",
        description: "Plate squeeze press for inner chest",
      },
      {
        name: "Dips",
        category: "Bodyweight",
        muscleGroup: "Chest",
        description: "Chest-focused parallel bar dips",
      },
      {
        name: "Floor Press",
        category: "Strength",
        muscleGroup: "Chest",
        description: "Barbell press performed on the floor",
      },
      {
        name: "Machine Chest Press",
        category: "Strength",
        muscleGroup: "Chest",
        description: "Seated machine chest press",
      },

      // Back
      {
        name: "Deadlift",
        category: "Strength",
        muscleGroup: "Back",
        description: "Conventional deadlift",
      },
      {
        name: "Pull-up",
        category: "Bodyweight",
        muscleGroup: "Back",
        description: "Standard pull-up",
      },
      {
        name: "Lat Pulldown",
        category: "Strength",
        muscleGroup: "Back",
        description: "Wide-grip lat pulldown",
      },
      {
        name: "Barbell Row",
        category: "Strength",
        muscleGroup: "Back",
        description: "Bent over barbell row",
      },
      {
        name: "T-Bar Row",
        category: "Strength",
        muscleGroup: "Back",
        description: "T-bar row machine",
      },
      {
        name: "Seated Cable Row",
        category: "Strength",
        muscleGroup: "Back",
        description: "Seated cable row",
      },
      {
        name: "Single-Arm DB Row",
        category: "Strength",
        muscleGroup: "Back",
        description: "Dumbbell row with one arm",
      },
      {
        name: "Meadows Row",
        category: "Strength",
        muscleGroup: "Back",
        description: "Landmine single-arm row variation",
      },
      {
        name: "Chin-Up",
        category: "Bodyweight",
        muscleGroup: "Back",
        description: "Underhand grip pull-up",
      },
      {
        name: "Straight-Arm Pulldown",
        category: "Strength",
        muscleGroup: "Back",
        description: "Cable pulldown with straight arms",
      },
      {
        name: "Good Morning",
        category: "Strength",
        muscleGroup: "Back",
        description: "Posterior chain exercise with barbell",
      },

      // Legs
      {
        name: "Squat",
        category: "Strength",
        muscleGroup: "Legs",
        description: "Barbell back squat",
      },
      {
        name: "Leg Press",
        category: "Strength",
        muscleGroup: "Legs",
        description: "Machine leg press",
      },
      {
        name: "Romanian Deadlift",
        category: "Strength",
        muscleGroup: "Legs",
        description: "Romanian deadlift",
      },
      {
        name: "Leg Extension",
        category: "Strength",
        muscleGroup: "Legs",
        description: "Machine leg extension",
      },
      {
        name: "Leg Curl",
        category: "Strength",
        muscleGroup: "Legs",
        description: "Lying leg curl",
      },
      {
        name: "Calf Raise",
        category: "Strength",
        muscleGroup: "Legs",
        description: "Standing calf raise",
      },
      {
        name: "Bulgarian Split Squat",
        category: "Strength",
        muscleGroup: "Legs",
        description: "Single-leg split squat",
      },
      {
        name: "Front Squat",
        category: "Strength",
        muscleGroup: "Legs",
        description: "Barbell front-loaded squat",
      },
      {
        name: "Walking Lunge",
        category: "Strength",
        muscleGroup: "Legs",
        description: "Walking dumbbell lunges",
      },
      {
        name: "Goblet Squat",
        category: "Strength",
        muscleGroup: "Legs",
        description: "Kettlebell or dumbbell front squat",
      },
      {
        name: "Hack Squat",
        category: "Strength",
        muscleGroup: "Legs",
        description: "Machine hack squat",
      },
      {
        name: "Seated Calf Raise",
        category: "Strength",
        muscleGroup: "Legs",
        description: "Seated machine calf raise",
      },
      {
        name: "Box Jump",
        category: "Functional",
        muscleGroup: "Legs",
        description: "Explosive jump onto box",
      },

      // Shoulders
      {
        name: "Overhead Press",
        category: "Strength",
        muscleGroup: "Shoulders",
        description: "Barbell overhead press",
      },
      {
        name: "Lateral Raise",
        category: "Strength",
        muscleGroup: "Shoulders",
        description: "Dumbbell lateral raise",
      },
      {
        name: "Front Raise",
        category: "Strength",
        muscleGroup: "Shoulders",
        description: "Dumbbell front raise",
      },
      {
        name: "Face Pull",
        category: "Strength",
        muscleGroup: "Shoulders",
        description: "Cable face pull",
      },
      {
        name: "Reverse Fly",
        category: "Strength",
        muscleGroup: "Shoulders",
        description: "Bent over dumbbell reverse fly",
      },
      {
        name: "Arnold Press",
        category: "Strength",
        muscleGroup: "Shoulders",
        description: "Dumbbell rotational shoulder press",
      },
      {
        name: "Upright Row",
        category: "Strength",
        muscleGroup: "Shoulders",
        description: "Barbell upright row",
      },
      {
        name: "Z-Press",
        category: "Strength",
        muscleGroup: "Shoulders",
        description: "Seated floor press",
      },
      {
        name: "Push Press",
        category: "Strength",
        muscleGroup: "Shoulders",
        description: "Explosive overhead press",
      },
      {
        name: "KB Bottoms-Up Press",
        category: "Strength",
        muscleGroup: "Shoulders",
        description: "Kettlebell upside-down press",
      },

      // Arms
      {
        name: "Bicep Curl",
        category: "Strength",
        muscleGroup: "Arms",
        description: "Dumbbell bicep curl",
      },
      {
        name: "Hammer Curl",
        category: "Strength",
        muscleGroup: "Arms",
        description: "Dumbbell hammer curl",
      },
      {
        name: "Tricep Extension",
        category: "Strength",
        muscleGroup: "Arms",
        description: "Overhead tricep extension",
      },
      {
        name: "Tricep Pushdown",
        category: "Strength",
        muscleGroup: "Arms",
        description: "Cable tricep pushdown",
      },
      {
        name: "Skull Crusher",
        category: "Strength",
        muscleGroup: "Arms",
        description: "Lying tricep extension",
      },
      {
        name: "Preacher Curl",
        category: "Strength",
        muscleGroup: "Arms",
        description: "Bicep curl using preacher bench",
      },
      {
        name: "EZ Bar Curl",
        category: "Strength",
        muscleGroup: "Arms",
        description: "Bicep curl with EZ curl bar",
      },
      {
        name: "Spider Curl",
        category: "Strength",
        muscleGroup: "Arms",
        description: "Prone bench bicep curl",
      },
      {
        name: "Close-Grip Bench",
        category: "Strength",
        muscleGroup: "Arms",
        description: "Close grip bench press for triceps",
      },
      {
        name: "Dip Machine",
        category: "Strength",
        muscleGroup: "Arms",
        description: "Machine tricep dips",
      },
      {
        name: "Cross-Body Hammer",
        category: "Strength",
        muscleGroup: "Arms",
        description: "Cross-body hammer curl",
      },

      // Core
      {
        name: "Plank",
        category: "Bodyweight",
        muscleGroup: "Core",
        description: "Standard plank position",
      },
      {
        name: "Crunch",
        category: "Bodyweight",
        muscleGroup: "Core",
        description: "Standard crunch",
      },
      {
        name: "Russian Twist",
        category: "Bodyweight",
        muscleGroup: "Core",
        description: "Seated russian twist",
      },
      {
        name: "Leg Raise",
        category: "Bodyweight",
        muscleGroup: "Core",
        description: "Lying leg raise",
      },
      {
        name: "Ab Wheel",
        category: "Strength",
        muscleGroup: "Core",
        description: "Ab wheel rollout",
      },
      {
        name: "Cable Crunch",
        category: "Strength",
        muscleGroup: "Core",
        description: "Kneeling cable crunch",
      },
      {
        name: "Mountain Climber",
        category: "Bodyweight",
        muscleGroup: "Core",
        description: "Plank position knee drives",
      },
      {
        name: "Hanging Leg Raise",
        category: "Bodyweight",
        muscleGroup: "Core",
        description: "Leg raise from hanging position",
      },
      {
        name: "Dead Bug",
        category: "Bodyweight",
        muscleGroup: "Core",
        description: "Core stability exercise",
      },
      {
        name: "Bird Dog",
        category: "Bodyweight",
        muscleGroup: "Core",
        description: "Quadruped limb extension",
      },
      {
        name: "Pallof Press",
        category: "Strength",
        muscleGroup: "Core",
        description: "Anti-rotation cable press",
      },
      {
        name: "Hollow Hold",
        category: "Bodyweight",
        muscleGroup: "Core",
        description: "Gymnastics core exercise",
      },

      // Cardio & Endurance
      {
        name: "Running",
        category: "Cardio",
        muscleGroup: "Full Body",
        description: "Distance running",
        measurementType: "distance_time",
        isEndurance: true,
      },
      {
        name: "Cycling",
        category: "Cardio",
        muscleGroup: "Legs",
        description: "Stationary or road cycling",
        measurementType: "distance_time",
        isEndurance: true,
      },
      {
        name: "Rowing",
        category: "Cardio",
        muscleGroup: "Full Body",
        description: "Rowing machine",
        measurementType: "distance_time",
        isEndurance: true,
      },
      {
        name: "Swimming",
        category: "Cardio",
        muscleGroup: "Full Body",
        description: "Lap swimming",
        measurementType: "laps",
        isEndurance: true,
      },
      {
        name: "Ski Erg",
        category: "Cardio",
        muscleGroup: "Full Body",
        description: "Ski ergometer",
        measurementType: "calories",
        isEndurance: true,
      },
      {
        name: "Jump Rope",
        category: "Cardio",
        muscleGroup: "Full Body",
        description: "Skipping rope",
        measurementType: "time_only",
        isEndurance: true,
      },
      {
        name: "Sled Push",
        category: "Endurance",
        muscleGroup: "Full Body",
        description: "Pushing weight sled",
        measurementType: "distance_only",
        isEndurance: true,
      },
      {
        name: "Assault Bike",
        category: "Cardio",
        muscleGroup: "Full Body",
        description: "Air bike",
        measurementType: "calories",
        isEndurance: true,
      },
      {
        name: "Burpee",
        category: "Endurance",
        muscleGroup: "Full Body",
        description: "Full body exercise",
        measurementType: "reps_only",
        isEndurance: true,
      },
      {
        name: "Battle Ropes",
        category: "Endurance",
        muscleGroup: "Full Body",
        description: "Rope wave exercise",
        measurementType: "time_only",
        isEndurance: true,
      },

      // HIIT & Functional
      {
        name: "Box Jumps",
        category: "Functional",
        muscleGroup: "Legs",
        description: "Jump onto raised platform",
        measurementType: "height",
        isEndurance: true,
      },
      {
        name: "Medicine Ball Slam",
        category: "Functional",
        muscleGroup: "Full Body",
        description: "Overhead med ball slam",
        measurementType: "reps_only",
      },
      {
        name: "Wall Ball",
        category: "Functional",
        muscleGroup: "Full Body",
        description: "Med ball squat and throw",
        measurementType: "reps_only",
        isEndurance: true,
      },
      {
        name: "Kettlebell Swing",
        category: "Functional",
        muscleGroup: "Full Body",
        description: "Hip-hinge KB swing",
        measurementType: "reps_only",
      },
      {
        name: "Farmer's Carry",
        category: "Functional",
        muscleGroup: "Full Body",
        description: "Weighted walking",
        measurementType: "distance_time",
      },
      {
        name: "Sandbag Carry",
        category: "Functional",
        muscleGroup: "Full Body",
        description: "Carrying sandbag",
        measurementType: "distance_time",
        isEndurance: true,
      },
      {
        name: "Tire Flip",
        category: "Functional",
        muscleGroup: "Full Body",
        description: "Flipping large tire",
        measurementType: "reps_only",
      },
      {
        name: "TRX Row",
        category: "Functional",
        muscleGroup: "Back",
        description: "Suspension trainer row",
        measurementType: "reps_only",
      },
      {
        name: "TRX Push-up",
        category: "Functional",
        muscleGroup: "Chest",
        description: "Suspension trainer push-up",
        measurementType: "reps_only",
      },
      {
        name: "Ladder Drills",
        category: "Functional",
        muscleGroup: "Full Body",
        description: "Agility ladder exercises",
        measurementType: "time_only",
        isEndurance: true,
      },
    ]);
}
