export const workoutPanel = `
<div id="training-hub" class="card hero">
  <div class="workout-head"><div><p class="eyebrow">YOUR TRAINING JOURNAL</p><h2>Every set counts.</h2><p class="muted">Log your lifts. Remember your last session. See your progress.</p></div><span class="badge">Saved to your Strive account</span></div>
  <p id="training-message" role="status" class="notice">Loading your training…</p>
  <form id="training-auth" hidden>
    <p class="notice">Sign in to save workouts across sessions. Your WHOOP test connection is separate from your Strive account.</p>
    <div class="log-fields"><label>Email<input name="email" type="email" autocomplete="username" required></label><label>Password<input name="password" type="password" autocomplete="current-password" minlength="8" maxlength="128" required></label><label id="name-field" hidden>Your name<input name="displayName" minlength="2" maxlength="80" autocomplete="name"></label></div>
    <div class="actions"><button class="button" type="submit" id="auth-submit">Sign in</button><button class="button secondary" type="button" id="auth-toggle">Create an account</button></div>
  </form>
  <div id="training-home" hidden>
    <div class="actions"><button class="button" id="new-workout">Build a workout +</button><button class="button secondary" id="show-history">History</button><button class="button secondary" id="show-records">Personal records</button><button class="button secondary" id="training-signout">Sign out</button></div>
    <div id="training-active"></div><div id="training-templates"></div>
  </div>
</div>
<section id="training-builder" class="card" hidden><p class="eyebrow">MAKE IT YOURS</p><h2>Build your session.</h2><p class="notice">Choose exact movements so records stay comparable. Log dumbbells per hand, barbells including the bar, and machines using the displayed load. Keep the same equipment and convention each time.</p><label>Workout name<input id="builder-name" maxlength="160" value="My workout"></label><label>Planned duration (minutes)<input id="builder-duration" type="number" min="1" max="240" step="1" value="45"></label><div id="builder-exercises"></div><div class="actions"><button class="button secondary" id="add-exercise">Add exercise</button><button class="button" id="start-built">Save & start workout</button><button class="button secondary" id="close-builder">Cancel</button></div></section>
<section id="training-session" hidden></section>
<section id="training-history" class="card" hidden><p class="eyebrow">SHOWING UP ADDS UP</p><h2>Your workout history.</h2><div id="history-list"></div></section>
<section id="training-records" class="card" hidden><p class="eyebrow">YOUR OWN BENCHMARKS</p><h2>Personal records.</h2><p class="notice">Completed workouts only. Heaviest load and best single-set volume (kg × reps) are separate records. Your first session establishes a baseline; ties are not new PRs. Compare the same exercise, equipment and loading convention.</p><div id="records-list"></div></section>
<style>
#workout input:not([type=checkbox]){display:block;width:100%;min-width:0;background:var(--bg);color:var(--ink);border:1px solid var(--line);border-radius:10px;padding:11px;margin:6px 0 12px} .log-fields{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:12px}.journal-row{display:flex;justify-content:space-between;align-items:center;gap:14px;border-top:1px solid var(--line);padding:16px 0}.journal-row p{margin-top:5px}.set-entry{display:grid;grid-template-columns:34px 1fr 1fr 1fr auto;align-items:end;gap:9px;padding:13px 0;border-top:1px solid var(--line)}.set-entry .button{margin-bottom:12px}.set-entry .set-index{align-self:center}.saved-set{color:var(--mint)}.session-stats{display:flex;gap:25px;flex-wrap:wrap;margin-top:18px}.session-stats strong{display:block;font-size:25px}.timer-card{position:sticky;top:8px;z-index:2;background:#203b32;border:1px solid #638f78;padding:14px 20px;border-radius:16px;display:flex;align-items:center;justify-content:space-between;gap:15px;margin-bottom:20px}.timer-card strong{font-size:23px;font-variant-numeric:tabular-nums}.record-pill{display:inline-block;background:#304638;color:var(--mint);border:1px solid #607950;padding:5px 9px;border-radius:9px;margin:4px;font-size:13px}.builder-row{border-top:1px solid var(--line);padding:15px 0}.training-error{color:#ffc4b6!important}@media(max-width:600px){.log-fields{grid-template-columns:1fr 1fr}.set-entry{grid-template-columns:25px 1fr 1fr 1fr}.set-entry .button{grid-column:2/5;margin:0}.journal-row{flex-wrap:wrap}.timer-card{top:0}.set-entry label{font-size:12px}}
</style>`;
